---

# todo: 
# * version asl var von aussen
# * current/latest links 
# * rollback (ggf. in eigenem play)

- name: stop demo-app
  service: name=demo-app state=stopped

- name: deploy demo-app
  copy: 
    src=../deployment/demo-app.jar
    dest={{application_path}}/demo-app.jar 
    owner={{application_user}}
    group={{application_group}}
    mode=0644

- name: start demo-app
  service: name=demo-app state=started
