---

# todo: 
# * version asl var von aussen
# * current/latest links 
# * rollback (ggf. in eigenem play)

- debug: msg={{ inventory_hostname }}

- name: remove host from loadbalancer pool
  haproxy: state=disabled host={{ inventory_hostname }} backend=webnodes
  delegate_to: lb

- name: stop demo-app
  service: name=demo-app state=stopped

- name: deploy demo-app
  copy: 
    src=../deployment/demo-app-{{demo_app_version}}.jar
    dest={{application_path}}/demo-app.jar 
    owner={{application_user}}
    group={{application_group}}
    mode=0644

- name: start demo-app
  service: name=demo-app state=started

- name: wait for demo-app to become available
  wait_for: port=8080 timeout=90

- name: add host back to loadbalancer pool
  haproxy: state=enabled host={{ inventory_hostname }} backend=webnodes
  delegate_to: lb