---

- name: create deployment folder
  file: path={{application_path}} state=directory mode=0755

- name: create init script
  template: 
    src=init-script.j2 
    dest=/etc/init.d/demo-app 
    owner=root
    group=root
    mode=0755

- name: stat remote application file
  stat: path={{ application_path }}/demo-app.jar
  register: remote_app_file

- name: stat local application file
  stat: path=../deployment/demo-app-{{demo_app_version}}.jar
  sudo: false
  delegate_to: localhost
  register: local_app_file

- name: run deployment if a new version is available
  include: deployment.yml
  when: not remote_app_file.stat.exists or ( local_app_file.stat.exists and ( remote_app_file.stat.md5 != local_app_file.stat.md5 ))
