---

- name: add apt repository for haproxy
  apt_repository: repo='ppa:vbernat/haproxy-1.5'

- name: install haproxy
  apt: name=haproxy state=installed

- name: create haproxy configuration
  template: 
    src=haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    owner=root
    group=root
    mode=0644

- name: start haproxy
  service: name=haproxy state=started enabled=true
