---

- name: create group for application
  group: name=app state=present

- name: create user for application
  user: 
    name=app
    group=app
    state=present
    shell=/usr/sbin/nologin
    createhome=no
